language: node_js
node_js: 8
cache: yarn

_production-env: &production-env
  ENVIRONMENT: production
  RANCHER_CLUSTERID: c-gxsr7

# _staging-env: &staging-env
#   ENVIRONMENT: staging
#   RANCHER_CLUSTERID: c-rc5kp

_production-job: &production-job
  stage: production
  node_js: 10
  name: SERVICE_NAME
  script: scripts/deploy.js SERVICE_NAME
  install: skip
  env:
    <<: *production-env

# _staging-job: &staging-job
#   stage: staging
#   node_js: 10
#   name: SERVICE_NAME
#   script: scripts/deploy.js SERVICE_NAME
#   install: skip
#   env:
#     <<: *staging-env

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

  # - name: staging-started
  #   if: tag is present
  # - name: staging
  #   if: tag is present
  # - name: staging-finished
  #   if: tag is present

jobs:
  include:
    - stage: test
      env:
        NODE_ENV: test

    - <<: *production-job
      stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started

    # - <<: *staging-job
    #   stage: staging-started
    #   name: Deployment Started
    #   script: npx @base-cms/website-deployment-tool notify-started

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - <<: *production-job
      name: GraphQL Service
      script: scripts/deploy.js graphql
    # - <<: *staging-job
    #   name: GraphQL Service
    #   script: scripts/deploy.js graphql

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    - <<: *production-job
      stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished

    # - <<: *staging-job
    #   stage: staging-finished
    #   name: Deployment Finished
    #   script: npx @base-cms/website-deployment-tool notify-finished
